services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: enders-app
    container_name: enders-app
    restart: unless-stopped
    working_dir: /var/www/enders
    volumes:
      - ./:/var/www/enders
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    networks:
      - enders-network
    depends_on:
      - db

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: enders-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/enders
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - enders-network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: enders-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-enders_db}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - enders-network
    ports:
      - "3307:3306"

networks:
  enders-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
